name: Send Mail
on: pull

jobs:
 Mails:
  runs-on: ubuntu-latest
  steps:
  - name: Print YogeshL
    run: echo "Helo world!"
  - name: Sending a Mails
    if: ${{ always() }}
    uses: devellany/send-mailer@v1.0.2
    with:
    host: smtp.google.com
      # Optional port (defaults to 465)
      port: 465
      account: ${{secrets.MAIL_USERNAME}}
      password: ${{secrets.MAIL_PASSWORD}}
      sender: devellany
      from: Yogesh
      to: yogeshlc021@gmail.com
      subject: mail title.
      body: your messages.
      # Optional content type (defaults to text/plain)
      contentType: text/plain
      # Optional attachment files (JSON type. require property 'path')
      attachments: '[{"path":"README.md"}]'